### ISSUE TITLE
Chrome CORS support

### ISSUE THREAD

**Issue by fbotis** [monsur/enable-cors.org#22]
I might be useful to add below info on the website:

In order to support Chrome CORS support the server should include 

Access-Control-Allow-Headers : Origin, X-Requested-With, Content-Type, Accept

**Comment by monsur** [comment]
I don't think this is true specifically for Chrome. Please reopen this issue if you disagree.

The CORS spec lists Accept as a simple header and therefore should not be necessary in the Access-Control-Allow-Headers header.

Content-Type is only needed if the requested content type is not one of: application/x-www-form-urlencoded, multipart/form-data, or text/plain.

X-Requested-With is from JQuery and the latest versions of JQuery should not be automatically setting this: http://bugs.jquery.com/ticket/8423

Origin should not be necessary (otherwise all CORS requests would have to be preflighted). IMO the CORS spec should document this (perhaps by defining Origin as a simple request header).

**Comment by fbotis** [comment]
Yup, I think you're right. I was using  "Content-Type: application/xml; charset=UTF-8" in my request. In this case the server needs to include only

"Access-Control-Allow-Headers: Content-Type"

as you specified. I will set my server to include "X-Requested-With" as well since old jQuery versions are using it.

Thanks for making the things clear :+1:
