### ISSUE TITLE
Domain enable-cors.org expired.

### ISSUE THREAD

**Issue by pgodel** [monsur/enable-cors.org#66]

**Comment by monsur** [comment]
Michael, do you have the domain info for this? I don't think we ever transferred it over.

**Comment by mhausenblas** [comment]
I'm so sorry, I blame GoDaddy (that's always easy, right?). Reason was that they send these friggin useless reminder mails and I've overlooked it. I renewed it right now for another year (before I saw your issue here, @monsur ) and now on auto-renewal.

BTW, it's a good sign that users notice it, isn't it :)
